### ISSUE TITLE
CVDense not defined

### ISSUE THREAD

**Issue by rveltz** [JuliaDiffEq/Sundials.jl#152]
Dear developers,

I use to use the following (piece) of code for calling `cvode` which I had copied from package.

```julia
Sundials.@checkflag Sundials.CVodeSetUserData(mem, [f,r,d,p])
Sundials.@checkflag Sundials.CVodeSStolerances(mem, reltol, abstol)
Sundials.@checkflag Sundials.CVDense(mem, neq)
```

It seems it is not the valid way anymore and one has to declare a dense matrix like [here](https://github.com/JuliaDiffEq/Sundials.jl/blob/master/src/simple.jl#L168). Do I have to do this? I don't really want to deal with the matrix `A` myself.

Thank you for your help,

Best regards

Romain

**Comment by ChrisRackauckas** [comment]
>I use to use the following (piece) of code for calling cvode which I had copied from package.

That is from an old version which used an older version of Sundials (2.5). This library now wraps Sundials 3.1 which no longer includes `CVDense`. The direct interface is simply calls to Sundials 3.1 now. See the Sundials manual:

https://computation.llnl.gov/sites/default/files/public/cv_guide.pdf

There are handle types in src/handles.jl for helping with memory management. For most things I would recommend the common interface since it takes care of the memory management and options handling. Also, it implements the `integrator` interface so that gives you a common step-by-step tooling that matches everything else in Julia. The simplified interface still exists and you can also check upgraded code from there (remember that if you don't use the handles, you need to free the `mem`, the matrix, and the linear solver).

If you need a previous version, you can pin to a version of Sundials.jl before v1.0.0 and re-run `Pkg.build("Sundials")` (you may need to wipe your `deps` folder first of everything but `build.jl`). But note that Sundials 3.1 is a superset of the features from Sundials 2.5 so everything from there is possible now, with of course new things added. The only breaking syntax change is really the matrix allocation and the linear solver, which used to be combined into `CVDense` but is now two lines of code instead of one (and requires freeing separately from the `mem`). However, that flexibility to use different matrix types and manually setting linear solvers is one of the biggest benefits of Sundials 3.0+, so I wouldn't see us going back on it.

If you do pin to a previous version, note that the direct interface Sundials documentation to use is the 2.4.0 version from 2009 on this page:

https://computation.llnl.gov/projects/sundials/sundials-software
