### ISSUE TITLE
new tagn

### ISSUE THREAD

**Issue by rveltz** [JuliaDiffEq/Sundials.jl#82]
Hi,

Can you tag 0.2.2+ as I need it for PDMP.jl?

Thank you for your help,

Romai

**Comment by ChrisRackauckas** [comment]
I see what you need. You can for CI run a separate script that will do the checkout, checkout out some of DifferentialEquations.jl's CI scripts to see how that's done (for ODE.jl, it no longer does it for Sundials and those tests are disabled for reasons similar to this).

We will be tagging when #75 is complete because that's another potentially breaking API change. To accommodate this request, I'm going to cut down the #75 to barebones and push it out ASAP (this weekend?) so this can be checked and tagged. All of the other issues about adding to it can be addressed later. (Sorry I hit a time crunch and this got delayed a bit!)

**Comment by rveltz** [comment]
OK, thank you for the suggestion

**Comment by ChrisRackauckas** [comment]
@alyst is it fine if I tag? The only API change in the current master is the addition of `cvode_fulloutput`, so the API is still backwards compatible if released right now. I think we should tag (minor release) and then pull in the API changes, drop v0.4, and upgrade the Sundials version. It looks like the PRs are stalled (need reviews!) for now, so we might as well do it.

**Comment by alyst** [comment]
@ChrisRackauckas +1. Looks like a reasonable plan.

**Comment by ChrisRackauckas** [comment]
Done https://github.com/JuliaLang/METADATA.jl/pull/6780#event-826550638
